vtex-apps/my-account-commons

CHANGELOG.md
manifest.json
package.json
react/ProgressBarBundle.js

- Fix `PackageProgress` exportation

Fix PackageProgress exportation

---

CHANGELOG.md
manifest.json
package.json
react/SkeletonBox.js
react/SkeletonPiece.js
react/style.global.css

Provide Skeleton components
Consistency in apps that use them.
n/a
n/a

Provide Skeleton components

---

CHANGELOG.md
manifest.json
messages/context.json
package.json

Bumps messages builder major

---

CHANGELOG.md
manifest.json
package.json

Release v0.8.1

---

CHANGELOG.md
manifest.json
package.json

Release v0.8.2

---

CHANGELOG.md
README.md
manifest.json
package.json
react/Router.js

Add file to export react-router-dom library.
Encapsulate react-router-dom for all my-account apps, so there will be no more version problems

Fix import react router

---

CHANGELOG.md
manifest.json
package.json

alert.connectionError update message

alert.connectionError update message

---

CHANGELOG.md
messages/de.json
package.json
yarn.lock

Add DE translations

---

CHANGELOG.md
messages/it.json

update Italian translations

---

CHANGELOG.md
manifest.json
messages/it.json
package.json

Same as https://github.com/vtex-apps/my-account-commons/pull/25 for `1.x`.

Update IT i18n

---

CHANGELOG.md
messages/it.json

Same as #30 but at 1.x
> #### What is the purpose of this pull request?
> Fix Italian message.
> 
> #### What problem is this solving?
> It was wrong.
> 
> #### How should this be manually tested?
> bianca--miriadeit.myvtex.com/
> 
> #### Types of changes
> 
> - [x] Bug fix (a non-breaking change which fixes an issue)
> - [ ] New feature (a non-breaking change which adds functionality)
> - [ ] Breaking change (fix or feature that would cause existing functionality to change)
> - [ ] Requires change to documentation, which has been updated accordingly.
>

Fix it translations @1.x

---

CHANGELOG.md
messages/it.json

Fix Italian message.
It was wrong.
bianca--miriadeit.myvtex.com/

Fix it translations @0.x

---

CHANGELOG.md
package.json
react/components/ProgressBar/constants.ts
react/components/ProgressBar/getOrderProgress.ts
react/components/ProgressBar/utils.ts
react/package.json
react/yarn.lock
yarn.lock

Add a new timeline flow for pickup orders.
Before this change, pickup orders were having the same treatment as any order, making some customers confused since the timeline said things like "shipping order" when it actually should be "sending order to pickup point".
https://villar--alssports.myvtex.com/
Before:
After:

[POST-128] Feature/add pickup timeline@1.x

---

CHANGELOG.md
package.json
react/components/ProgressBar/constants.ts
react/components/ProgressBar/getOrderProgress.ts
react/components/ProgressBar/utils.ts
react/package.json
react/yarn.lock
yarn.lock

Same as #29 but at 0.x
>#### What is the purpose of this pull request?
> Add a new timeline flow for pickup orders.
> 
> #### What problem is this solving?
> Before this change, pickup orders were having the same treatment as any order, making some customers confused since the timeline said things like "shipping order" when it actually should be "sending order to pickup point".
> 
> #### How should this be manually tested?
> https://villar--alssports.myvtex.com/
> 
> #### Screenshots or example usage
> Before:
> ![image](https://user-images.githubusercontent.com/27328184/86492996-37380500-bd46-11ea-863d-65a0a9ead90c.png)
> 
> After:
> ![image](https://user-images.githubusercontent.com/27328184/86492967-24253500-bd46-11ea-94f0-ae1807a56881.png)

[POST-128] Feature/add pickup timeline@0.x

---

CHANGELOG.md
manifest.json
react/components/ContentWrapper.js
react/package.json
react/utils.js
react/yarn.lock

Prevent back button from being hidden when in mobile phones.
Without it, people are unable to exit my-account. [See](https://vtex.slack.com/archives/C91LXBHLK/p1594402249014400).
https://cobasi.myvtex.com/_secure/account?workspace=villar#/profile
It stills hides in desktops, but appears in mobile phones.

Fix mobile back button@0.x

---

CHANGELOG.md

Add changelog and release the changes made in PR #14

Add changelog for pr #40

---

CHANGELOG.md
react/__tests__/utils.js
react/utils.js

This PR is the same as #40 and #41

Fix/shipping estimate without unit 1.x

---

CHANGELOG.md
react/ProgressBarBundle.js
react/components/ProgressBar/utils.ts
react/package.json
react/yarn.lock

This PR is the same as #46 adapted to the 0.x version.

Change/status badge behavior 0.x

---

CHANGELOG.md
messages/es.json

It relates to task [LOC-11299](https://vtex-dev.atlassian.net/browse/LOC-11299). Fixes a Spanish string that is supposed to be "Atrás".
[LOC-11299]: https://vtex-dev.atlassian.net/browse/LOC-11299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix of a spanish string

---

CHANGELOG.md
react/components/ProgressBar/utils.ts

Same as https://github.com/vtex-apps/my-account-commons/pull/73.

[Fix][OMS-4482] Fix isDelivered function
